### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by ruxi** [takluyver/cite2c#17]
ruxi@lifemint ~/git/cite2c $ ./install.py
from: can't read /var/mail/os.path
from: can't read /var/mail/IPython.html.nbextensions
from: can't read /var/mail/IPython.html.services.config
./install.py: line 5: syntax error near unexpected token `"Installing nbextension ..."'
./install.py: line 5: `print("Installing nbextension ...")'

**Comment by takluyver** [comment]
Oh, it's missing a shebang. If you do `python install.py`, it should work.

**Comment by ruxi** [comment]
Just tried and it worked :)

Thanks!

**Comment by takluyver** [comment]
You're welcome. I've hopefully just fixed it, too.
