### ISSUE TITLE
unable to search zotoro user library

### ISSUE THREAD

**Issue by ruxi** [takluyver/cite2c#18]
I think the zotero api now requires a private key to access bibliography information. I tried inputing my userID, but the bibliography info is not showing up. 

https://www.zotero.org/settings/keys

Has anyone else had success accessing zotero with this extension recently?

**Comment by takluyver** [comment]
It was working for me the other day (give or take some UI issues that we're trying to work out).

Note that you do currently need to go to [privacy settings](https://www.zotero.org/settings/privacy) and tick 'publish my entire library'. I do mean to look into OpenID at some point, but it's rather complex. See also #9.

**Comment by ruxi** [comment]
Didn't see the 'publish my entire library' option. Thanks! That did the trick

**Comment by takluyver** [comment]
I've finally got round to implementing OAuth, so the 'publish my entire library' setting is no longer needed in master.
