### ISSUE TITLE
Does not work in nbviewer?

### ISSUE THREAD

**Issue by moxpower** [takluyver/cite2c#28]
Hi, nice tool! Is there a way to make it work on gitHub and the nbviewer? Currently, no content is displayed, neither the citation, nor the bibliography. Thanks!

**Comment by takluyver** [comment]
Thanks :-). No, that's something I need to get round to fixing (see #10). I've just got back from a series of trips, so hopefully I'll have some more time coming up to work on stuff.

**Comment by moxpower** [comment]
Sounds fantastic! Let me know when you need a helping hand.
