### ISSUE TITLE
Privacy settings in zotero

### ISSUE THREAD

**Issue by wtbarnes** [takluyver/cite2c#29]
The README should mention that it is necessary to check the "Publish entire library" setting in "Settings->Privacy" in the Zotero webapp. Otherwise, none of your citations will show up since there is no auth being done. Thanks to [this blog post](http://blog.juliusschulz.de/blog/ultimate-ipython-notebook#cite2c) for pointing this out.

**Comment by takluyver** [comment]
Agreed, it should. PRs welcome, or I'll try to get round to this.

**Comment by takluyver** [comment]
I've finally got round to implementing OAuth, which means it's no longer necessary to make your library public to use cite2c. I'll try to make a new release soon.
