### ISSUE TITLE
I can't execute the cite2c/main.

### ISSUE THREAD

**Issue by huangteng1220** [takluyver/cite2c#32]
I had install cite2c/main. But in my configurable nbextensions, the cite2/main is gray as following figure  , it can't be used. Why? Would you help me? Thank you very much.

![Uploading A9174681-3AED-4CE2-BF34-842248A1E58F.png…]()

**Comment by takluyver** [comment]
Sorry for the very delayed reply. It looks like the screenshot didn't upload properly. I don't know what the problem was, so I hope you worked it out somehow.

**Comment by mticlla** [comment]
Here a screenshot of mine
![image](https://user-images.githubusercontent.com/8407676/34948711-3bdaa7be-fa0e-11e7-980b-d8e3a976e06d.png)

**Comment by mticlla** [comment]
Python 3.5.2
Jupyter 4.4.0

After executing `jupyter nbextension enable cite2c/main`
![image](https://user-images.githubusercontent.com/8407676/34948880-b0802c38-fa0e-11e7-8b5b-5e841271e289.png)

But when Zotero authentication is required, the new tab just says
![image](https://user-images.githubusercontent.com/8407676/34949262-e2209696-fa0f-11e7-8714-df44e4221e72.png)

**Comment by takluyver** [comment]
Can you run `python -m cite2c.install` to enable it? It's got a server part and a frontend part, and I think you've enabled the frontend part without the server part.

**Comment by mticlla** [comment]
Thanks Thomas, 
after running that line, got these messages
![image](https://user-images.githubusercontent.com/8407676/34961617-4efeb45c-fa40-11e7-9dbb-c094493931d0.png)

I then disable and re-enable cite2c/main, but I still have the same problem

**Comment by takluyver** [comment]
Can you look for a file `~/.jupyter/jupyter_notebook_config.json` and see what it's got in it?

**Comment by mticlla** [comment]
![image](https://user-images.githubusercontent.com/8407676/34962778-7af53900-fa45-11e7-93db-95f9c8509415.png)

**Comment by takluyver** [comment]
That looks right. Have you stopped the notebook server and launched it (`jupyter notebook`) again after enabling the extension?

**Comment by mticlla** [comment]
Yes, I even deactivates the virtual environment and then reactivated it, and then launched again jupyter notebook

**Comment by takluyver** [comment]
Is there anything that looks relevant in the logging to the terminal where you launched the notebook?

**Comment by mticlla** [comment]
Maybe that the server runs at an **https**://[all ip addresses on your system]:xxxx/tree

The authentication tab will look like:
**https**://[all ip addresses on your system]:xxxx/cite2c/zotero_oauth

could it be the https?

**Comment by mticlla** [comment]
The browser labels the connection as non-secure (because of a self-signed certificate)

**Comment by mticlla** [comment]
![image](https://user-images.githubusercontent.com/8407676/34963419-a042051e-fa48-11e7-8850-c54da4114a62.png)

**Comment by takluyver** [comment]
Oh,  I see the problem. In [this function](https://github.com/takluyver/cite2c/blob/0478bdeedd7c033768018c9e3a4f25e7d060ba95/cite2c/handlers.py#L27), it skips setting up the handlers if it can't find the Zotero styles directory. It should add the OAuth handlers even if the styles directory is missing, because the styles are completely separate.

I'm just about to go to bed, but hopefully that gives you enough info to get it working for now. Feel free to send a PR if you're comfortable doing so.

**Comment by mticlla** [comment]
Thanks a lot Thomas, I'm also almost going to bed. Will fix it tomorrow.

**Comment by mticlla** [comment]
I just commented the return line in [that function](https://github.com/takluyver/cite2c/blob/0478bdeedd7c033768018c9e3a4f25e7d060ba95/cite2c/handlers.py#L27) and now cite2c works in my notebooks :)
Thanks

**Comment by takluyver** [comment]
Great. And I've just released 0.2.1 with that issue fixed. :-)
