### ISSUE TITLE
nothing happens when clicking insert citation

### ISSUE THREAD

**Issue by marnec** [takluyver/cite2c#34]
I was trying to get the 'insert citation' feature to work but it couldn't fetch any papers, so I looked at the issues and found I had to make my Zotero librabry public. I did it but still no citations found.

So I tried to refresh my account name by setting it to None as suggested in #9. 
From that moment, whenever I click on insert citation nothing happens (I tried to reset my username correctly).

**Comment by takluyver** [comment]
Is there any error in the JavaScript console when that happens?

**Comment by marnec** [comment]
Sorry couldn't check on that.
After various days of non-use I tried again today and the prompt is here
again.
I still can't match any item from my public library but I guess this is
another issue.

**Comment by auriml** [comment]
Hi @takluyver , 

It seems that  just adding the apikey to the request could fix this issue: 
You can see here the Javascript console error --> 
![image](https://user-images.githubusercontent.com/26073453/33681582-4833c4fe-dac5-11e7-99bc-38bd669b1da0.png)

In essence: the following results in wrong api url:

'https://api.zotero.org/users/<userid>/items'

but the actual post url would work:

'https://api.zotero.org/users/<userid>/items?key=<apikey>;

I would appreciate if you could fix this issue. Thanks!

**Comment by takluyver** [comment]
If you make your library public in Zotero, it works. I think that to access non-public libraries we need to use Oauth (#9), which is a more complicated task than just adding an API key.

**Comment by takluyver** [comment]
And in trying to figure out just how complicated it would be, I appear to have nerd sniped myself into doing it. :roll_eyes: The version in master now uses OAuth to get an access token so it can read your library.

I'll make a release with this soon - any testing is welcome. :-)
