### ISSUE TITLE
can't install on mac

### ISSUE THREAD

**Issue by Tyelcie** [takluyver/cite2c#44]
Hi,

I've managed to install it on windows, but now I need to switch to mac. When I run `pip install cite2c` it said Successfully installed, but when comes to `python -m cite2c.install` it said No module named cite2c, and the two buttons never shows up.

 I can't figure out what's missing, can you help?

Thanks ahead!

**Comment by takluyver** [comment]
It's possible that `pip` installed it into a different Python version or environment from the one that `python` is found in. You can use `python -m pip install ...` to make sure you're installing things in that Python environment.

**Comment by Tyelcie** [comment]
Wow, `python -m pip install...` still don't work but said no module named pip, but since you mentioned environment, I tried `python3 -m cite2c.install` then it worked!

Thank you a lot ^_^

**Comment by takluyver** [comment]
You're welcome :-)
