### ISSUE TITLE
Is there a posibility to use this extension without zotero?

### ISSUE THREAD

**Issue by white-gecko** [takluyver/cite2c#46]
I don't have a zotero account and would like to use this extension just with my local bibtex file. Is this possible?

**Comment by takluyver** [comment]
This extension does not. If you're willing to reference citations by hand and only see them in latex/pdf output, then you can do so without this extension - see this example:

https://nbviewer.jupyter.org/github/jupyter/nbconvert-examples/blob/master/citations/Tutorial.ipynb
