### ISSUE TITLE
More user friendly connection to Zotero

### ISSUE THREAD

**Issue by takluyver** [takluyver/cite2c#9]
At present, the user has to go to a Zotero settings page, and copy down a user ID that is different from their username. This is less than ideal. I'd like to be able to just use their username, but I've yet to find an API to get the userID from the username. [Question on Zotero forums](https://forums.zotero.org/discussion/42131/get-userid-from-username/).

It's probably possible to do this using oauth ([docs](https://www.zotero.org/support/dev/web_api/v3/oauth)), but that's complicated. If we want access to private Zotero libraries, however, we will need to jump through that hoop. (Are user libraries public by default? I can't remember)

**Comment by bramtayl** [comment]
Stupid question how to you change your userID if you entered your actual name and not the number on the settings page?

**Comment by takluyver** [comment]
There's no way to change it in the UI, but you can set it manually by running code like this:

```python
from IPython.html.services.config.manager import ConfigManager
cm = ConfigManager()
cm.update('cite2c', {'zotero':{'user_id': '1234'}})
```

Or if you set it to `None` instead of an ID, it will prompt you again next time you go to use cite2c.

**Comment by bramtayl** [comment]
Great! It works perfectly. However, all my bibliographic information disappears when I try to export as html or pdf.

**Comment by takluyver** [comment]
Yeah, they will for now. HTML is issue #10 - that should be relatively easy to do using [citeproc-7py](https://pypi.python.org/pypi/citeproc-py/). Latex is issue #7, and it will be a bit trickier, because we'll need to convert the CSL citation data to Bibtex.
